pipeline {
    agent any
    tools { maven 'maven-3.9' }

    environment {
        AWS_ACCOUNT_ID = "952647925716"
        AWS_REGION     = "ap-southeast-2"
        IMAGE_REPO     = "bondhub/api-gateway"
        IMAGE_TAG      = "${env.BUILD_NUMBER}"
        ECR_URL        = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {
        stage('Setup Tools') {
            steps {
                script {
                    sh '''
                        echo "=== Installing Docker CLI ==="
                        if [ ! -x /usr/local/bin/docker ]; then
                            curl -L https://download.docker.com/linux/static/stable/x86_64/docker-27.3.1.tgz | tar -xz -C /tmp
                            mv /tmp/docker/docker /usr/local/bin/
                            ln -sf /usr/local/bin/docker /usr/bin/docker
                            rm -rf /tmp/docker
                        fi

                        echo "=== Installing kubectl ==="
                        if [ ! -x /usr/local/bin/kubectl ]; then
                            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                            chmod +x kubectl
                            mv kubectl /usr/local/bin/
                            ln -sf /usr/local/bin/kubectl /usr/bin/kubectl
                        fi

                        echo "=== Verification ==="
                        docker --version
                        kubectl version --client
                    '''
                }
            }
        }

        stage('Maven Build') {
            steps {
                dir('api-gateway') {
                    script {
                        sh 'mvn -f ../pom.xml install -N' 
                        sh 'mvn -f ../common/pom.xml clean install -DskipTests'
                        sh 'mvn clean package -DskipTests'
                    }
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    docker.withRegistry("https://${ECR_URL}", "ecr:${AWS_REGION}:aws-credentials-id") {
                        dir('api-gateway') {
                            def customImage = docker.build("${IMAGE_REPO}:${IMAGE_TAG}")
                            customImage.push()
                            customImage.push("latest")
                        }
                    }
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                withKubeConfig([credentialsId: 'eks-creds-id', clusterName: 'bondhub-cluster-final']) {
                    sh "kubectl set image deployment/api-gateway-deploy api-gateway=${ECR_URL}/${IMAGE_REPO}:${IMAGE_TAG} -n bondhub"
                }
            }
        }
    }
}
