pipeline {
    agent any
    tools { maven 'maven-3.9' }

    environment {
        AWS_ACCOUNT_ID = "952647925716"
        AWS_REGION     = "ap-southeast-2"
        IMAGE_REPO     = "bondhub/api-gateway"
        IMAGE_TAG      = "${env.BUILD_NUMBER}"
        ECR_URL        = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {
        stage('Wait for Infrastructure Tools') {
            steps {
                script {
                    echo "Checking for Docker and Kubectl at absolute paths..."
                    timeout(time: 5, unit: 'MINUTES') {
                        waitUntil {
                            def dockerCheck = sh(script: 'test -x /usr/local/bin/docker', returnStatus: true) == 0
                            def kubectlCheck = sh(script: 'test -x /usr/local/bin/kubectl', returnStatus: true) == 0
                            return (dockerCheck && kubectlCheck)
                        }
                    }
                    sh '/usr/local/bin/docker --version'
                    sh '/usr/local/bin/kubectl version --client'
                }
            }
        }

        stage('Maven Build') {
            steps {
                dir('api-gateway') {
                    script {
                        sh 'mvn -f ../pom.xml install -N' 
                        sh 'mvn -f ../common/pom.xml clean install -DskipTests'
                        sh 'mvn clean package -DskipTests'
                    }
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    docker.withRegistry("https://${ECR_URL}", "ecr:${AWS_REGION}:aws-credentials-id") {
                        dir('api-gateway') {
                            def customImage = docker.build("${IMAGE_REPO}:${IMAGE_TAG}")
                            customImage.push()
                            customImage.push("latest")
                        }
                    }
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                withKubeConfig([credentialsId: 'eks-creds-id', clusterName: 'bondhub-cluster-final']) {
                    sh "/usr/local/bin/kubectl set image deployment/api-gateway-deploy api-gateway=${ECR_URL}/${IMAGE_REPO}:${IMAGE_TAG} -n bondhub"
                }
            }
        }
    }
}
