spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  messages:
    basename: i18n/messages,i18n/messages-notification
    encoding: UTF-8
    fallback-to-system-locale: false

app:
  firebase:
    config-path: ${FIREBASE_CONFIG_PATH}
