pipeline {
    agent any
    tools { maven 'maven-3.9' }

    environment {
        AWS_ACCOUNT_ID = "952647925716"
        AWS_REGION     = "ap-southeast-2"
        IMAGE_REPO     = "bondhub/discovery-server"
        IMAGE_TAG      = "${env.BUILD_NUMBER}"
        ECR_URL        = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {
        stage('Wait for Infrastructure Tools') {
            steps {
                script {
                    echo "Waiting for Docker and Kubectl to be installed..."
                    timeout(time: 5, unit: 'MINUTES') {
                        waitUntil {
                            def dockerCheck = sh(script: 'command -v docker', returnStatus: true) == 0
                            def kubectlCheck = sh(script: 'command -v kubectl', returnStatus: true) == 0
                            return (dockerCheck && kubectlCheck)
                        }
                    }
                    sh 'docker --version'
                    sh 'kubectl version --client'
                }
            }
        }

        stage('Maven Build') {
            steps {
                dir('discovery-server') {
                    script {
                        sh 'mvn -f ../pom.xml install -N' 
                        sh 'mvn -f ../common/pom.xml clean install -DskipTests'
                        sh 'mvn clean package -DskipTests'
                    }
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    docker.withRegistry("https://${ECR_URL}", "ecr:${AWS_REGION}:aws-credentials-id") {
                        dir('discovery-server') {
                            def customImage = docker.build("${IMAGE_REPO}:${IMAGE_TAG}")
                            customImage.push()
                            customImage.push("latest")
                        }
                    }
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                withKubeConfig([credentialsId: 'eks-creds-id', clusterName: 'bondhub-cluster-final']) {
                    sh "kubectl set image deployment/discovery-server-deploy discovery-server=${ECR_URL}/${IMAGE_REPO}:${IMAGE_TAG} -n bondhub"
                }
            }
        }
    }
}
