apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: bondhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        node-type: infra
      securityContext:
        runAsUser: 0
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          env:
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
            - name: PATH
              value: "/var/jenkins_home/tools:/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
        # Docker-in-Docker sidecar
        - name: dind
          image: docker:27.3.1-dind
          securityContext:
            privileged: true
          args:
            - "--host=tcp://0.0.0.0:2375"
            - "--host=unix:///var/run/docker.sock"
            - "--storage-driver=overlay2"
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          ports:
            - containerPort: 2375
          volumeMounts:
            - name: docker-storage
              mountPath: /var/lib/docker
      volumes:
        - name: jenkins-data
          emptyDir: {}
        - name: docker-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: bondhub
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - port: 80
      targetPort: 8080
