package com.bondhub.common.enums;

public enum NotificationType {
    DOB,

    FRIEND_REQUEST,
    FRIEND_ACCEPT,

    MESSAGE_DIRECT,
    MESSAGE_GROUP,
    CALL,

    POST_REACTION,
    POST_COMMENT,
    POST_PUBLISHED,
    COMMENT_REACTION,
    COMMENT_REPLY,

    POST_TAG,
    POST_MENTION,
    COMMENT_MENTION,

    SYSTEM,

    DLQ_ALERT,

    // --- ACCOUNT SECURITY ---
    NEW_DEVICE_LOGIN,

    // --- MODERATION ---
    CONTENT_REMOVED,
    CONTENT_HIDDEN,
    USER_WARNED,

    DND_SUMMARY,
    DND_SUMMARY_MESSAGE,
    DND_SUMMARY_FRIEND,
    DND_SUMMARY_POST,
    DND_SUMMARY_OTHER
}
