package com.bondhub.common.enums;

public enum SystemActionType {
    CREATE_GROUP,
    ADD_MEMBERS,
    REMOVE_MEMBER,
    LEAVE_GROUP,
    UPDATE_NAME,
    UPDATE_AVATAR,
    DISBAND_GROUP,
    PROMOTE_ADMIN,
    DEMOTE_ADMIN,
    TRANSFER_OWNER,
    UPDATE_SETTINGS,
    JOIN_BY_LINK,
    GENERATE_JOIN_LINK,
    REFRESH_JOIN_LINK
}
