apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
  namespace: bondhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      nodeSelector:
        node-type: infra
      initContainers:
        - name: wait-for-discovery
          image: busybox
          command: ['sh', '-c', 'until nc -z bh-discovery-server 8761; do echo waiting for discovery; sleep 2; done;']
      containers:
        - name: api-gateway
          image: 952647925716.dkr.ecr.ap-southeast-2.amazonaws.com/bondhub/api-gateway:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: bondhub-common-config
            - secretRef:
                name: bondhub-common-secrets
