spring:
  application:
    name: common
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://bh-config-server:8888}"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://bh-config-server:8888}
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION} # 1 hour in milliseconds
  refresh:
    expiration-web: ${JWT_REFRESH_WEB_EXPIRATION} # 14 days in milliseconds
    expiration-mobile: ${JWT_REFRESH_MOBILE_EXPIRATION} # 365 days in milliseconds

# AWS S3 Configuration
cloud:
  aws:
    region:
      static: ${AWS_REGION}
aws:
  s3:
    bucket:
      name: ${AWS_S3_BUCKET_NAME}