server:
  port: 8083

spring:
  application:
    name: notification-service

  messages:
    basename: i18n/messages, i18n/messages-notification

  data:
    mongodb:
      uri: ${MONGODB_URI_NOTIFICATIONS}
      auto-index-creation: true
      uuid-representation: standard
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  kafka:
    producer:
      client-id: notification-service-producer

    consumer:
      group-id: noti-pipeline-group
      client-id: notification-service-consumer
      max-poll-records: 50
      properties:
        max.poll.interval.ms: 600000

    listener:
      concurrency: 4
      ack-mode: manual

notification:
  kafka:
    topics:
      raw: noti.raw
      ready: noti.ready

logging:
  level:
    com.bondhub.notificationservices: DEBUG
    org.springframework.mail: DEBUG
  file:
    name: logs/notification-service.log

resilience4j:
  circuitbreaker:
    instances:
      notificationService:
        base-config: default
  retry:
    instances:
      notificationService:
        base-config: default
  timelimiter:
    instances:
      notificationService:
        base-config: default

bondhub:
  security:
    public-endpoints: []

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: false
