apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deploy
  namespace: bondhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      nodeSelector:
        node-type: core-social
      initContainers:
        - name: wait-for-infra
          image: busybox
          command: ['sh', '-c', 'until nc -z bh-discovery-server 8761 && nc -z bh-config-server 8888; do echo waiting for infra services; sleep 2; done;']
      containers:
        - name: user-service
          image: 952647925716.dkr.ecr.ap-southeast-2.amazonaws.com/bondhub/user-service:latest
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: bondhub-common-config
            - secretRef:
                name: bondhub-common-secrets
